version: '4.8.1'
services:
    its462-db:
        container_name: its462-db
        image: mysql
        volumes:
            - ./data:/docker-entrypoint-initdb.d:ro
        environment:
          MYSQL_DATABASE: 'project'
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - "9906:3306"
