version: '3.4'

services:
  its462-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'project'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '9906:3306'
    expose:
      - '3306'
    volumes:
      - its462-db:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d:ro
# Names our volume
volumes:
  its462-db:
