version: '3.4'

services:
  its462-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'project'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '9906:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - its462-db:/var/lib/mysql
# Names our volume
volumes:
  its462-db:
